export const environment = {
  production: false,
  identityApiUrl: 'http://localhost:5001/api/identity',
  userApiUrl: 'http://localhost:5000/api/users',
  departamentApiUrl: 'http://localhost:5002/api/departaments',
  projectApiUrl: 'http://localhost:5003/api/projects',
  expenseAccountApiUrl: 'http://localhost:5006/api/expenseaccount',
  expenseReportApiUrl: 'http://localhost:5006/api/expensereport',
  expenseApiUrl: 'http://localhost:5006/api/expense',
  signatureApiUrl: 'http://localhost:5006/api/signature',
  fileApiUrl: 'http://localhost:5004/api/files',
  apiZipCodeToken: '',
  jwtToken: 'uNNtAoquY3kUMt1BsvLcUqf51rovyv2e',
  jwtDomain: 'http://localhost:5088',
};
